language: cpp

os:
  - linux
  - osx

services: docker
sudo: required
dist: xenial

matrix:
    fast_finish: true
    include:
        - compiler: clang
          dist: xenial
          env:
            - SCAN="scan-build --status-bugs"

addons:
    apt:
      sources:
        - sourceline: 'ppa:rrossgotterer/xenial-backports'
        - george-edison55-precise-backports # cmake 3
      packages:
        - cppcheck
        - cmake
        - cmake-data

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update && brew install cppcheck;
    fi

before_script:
  - mkdir build
  - pushd build
  - $SCAN cmake
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
            -DBUILD_SHARED_LIBS=ON
            -DCMAKE_BUILD_TYPE=Release
            -DCMAKE_INSTALL_NAME_DIR=/usr/local/lib
            ..
  - cppcheck --enable=style,portability,performance,warning
             --library=posix
             --suppressions-list=$TRAVIS_BUILD_DIR/cppcheck/suppressions.txt
             --inline-suppr
             --project=compile_commands.json
             --error-exitcode=1
             -DENDIANNESS_LITTLE_ENDIAN
  - popd

script:
  - pushd build
  - $SCAN make && ctest --output-on-failure
  - sudo make install
  - popd
