version: 1.0.{build}

configuration:
    - Release

os: Visual Studio 2015
image: Visual Studio 2015

platform:
    - x86
    - x64

matrix:
    fast_finish: true

environment:
    matrix:
        - PYTHON_DIR: "C:\\Python27"
        - PYTHON_DIR: "C:\\Python35"
        - PYTHON_DIR: "C:\\Python36"
        - PYTHON_DIR: "C:\\Python37"

before_build:
    - set PATH=%PYTHON_DIR%;%PATH%
    - set generator="Visual Studio 14 2015"
    - if "%platform%" == "x64" set generator="Visual Studio 14 2015 Win64"
    - if "%platform%" == "x64" set PYTHON_DIR=%PYTHON_DIR%-x64
    - git fetch --tags
    - python -m pip install -r python/requirements-dev.txt

build_script:
    - mkdir build
    - ps: pushd build
    - cmake %APPVEYOR_BUILD_FOLDER%
            -G %generator%
            -DCMAKE_CXX_FLAGS="/D_CRT_SECURE_NO_WARNINGS /EHsc"
    - cmake --build .  --config %configuration% --target install
    - ctest --build-config %configuration% --output-on-failure
    - ps: popd
    - ps: pushd python
    - python setup.py bdist_wheel -G %generator%
    - ps: popd
