version: 1.0.{build}

configuration:
    - Release

os: Visual Studio 2015
image: Visual Studio 2015

platform:
    - x86
    - x64

matrix:
    fast_finish: true

before_build:
    - set generator="Visual Studio 14 2015"
    - IF "%platform%" == "x64" set generator="Visual Studio 14 2015 Win64"
    - git fetch --tags

build_script:
    - ps: |
          mkdir build
          pushd build
    - cmake %APPVEYOR_BUILD_FOLDER%
            -G %generator%
            -DCMAKE_CXX_FLAGS="/D_CRT_SECURE_NO_WARNINGS /EHsc"
    - cmake --build .  --config %configuration%
    - ctest --build-config %configuration% --output-on-failure
