version: 2.1

commands:
  install_build_deps:
    parameters:
      sudo:
        type: boolean
        default: false
      extra:
        type: string
        default: ""
    steps:
      - run:
          name: install cmake gcc python3
          command: |
            <<#parameters.sudo >> sudo <</parameters.sudo >> apt-get update
            <<#parameters.sudo >> sudo <</parameters.sudo >> apt-get install \
            -y cmake g++ python3 python3-pip git << parameters.extra >>

  python_build:
    steps:
      - checkout
      - install_build_deps:
          sudo: true
      - run:
          name: install core
          command: |
            mkdir build
            cd build
            cmake -DBUILD_SHARED_LIBS=ON \
                  -DCMAKE_BUILD_TYPE=Release \
                  -DBUILD_TESTS=OFF \
                  -DBUILD_PYTHON=OFF \
                  ..
            make
            sudo make install
            sudo ldconfig /usr/local/lib
      - run:
          name: install python dependencies
          command: python -m pip install --user -r python/requirements-dev.txt
      - run:
          name: build python
          command: |
            cd python
            python setup.py build_ext --inplace install --user test

  cmake_build:
    description: ecl3 build steps
    parameters:
      type:
        description: build type
        type: enum
        default: Release
        enum: ["Release", "Debug", "RelWithDebInfo"]
      scan:
        description: scan-build or similar command prefix
        type: string
        default: ""
    steps:
      - run:
          name: install python extra
          command: python3 -m pip install --user -r python/requirements-dev.txt
      - run:
          name: configure
          command: |
            mkdir build
            cd build
            << parameters.scan >> \
            cmake -DBUILD_SHARED_LIBS=ON \
                  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
                  -DCMAKE_BUILD_TYPE=<< parameters.type >> \
                  -DPYTHON_EXECUTABLE=`which python3` \
                  ..
      - run:
          name: build and install
          command: << parameters.scan >> cmake --build build --target install
      - run:
          name: test
          command: |
            cd build
            ctest --output-on-failure

jobs:
  gcc:
    docker:
      - image: debian:stable
    steps:
      - checkout
      - install_build_deps
      - cmake_build

  clang:
    docker:
      - image: debian:stable
    environment:
      CC: /usr/bin/clang
      CXX: /usr/bin/clang++
    steps:
      - checkout
      - install_build_deps:
          extra: clang
      - cmake_build

  debug:
    docker:
      - image: debian:stable
    steps:
      - checkout
      - install_build_deps
      - cmake_build:
          type: Debug

  scan-build:
    docker:
      - image: debian:stable
    steps:
      - checkout
      - install_build_deps:
          extra: clang libfindbin-libs-perl
      - cmake_build:
          scan: scan-build --status-bugs

  cppcheck:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - install_build_deps:
          extra: cppcheck
      - run:
          name: run cppcheck
          command: |
            cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DBUILD_TESTING=OFF
            cppcheck --enable=style,portability,performance,warning \
                     --library=posix \
                     --suppressions-list=cppcheck/suppressions.txt \
                     --inline-suppr \
                     --project=compile_commands.json \
                     --error-exitcode=1

  python-27:
    docker:
      - image: circleci/python:2.7
    steps:
      - python_build

  python-35:
    docker:
      - image: circleci/python:3.5
    steps:
      - python_build

  python-36:
    docker:
      - image: circleci/python:3.6
    steps:
      - python_build

  python-37:
    docker:
      - image: circleci/python:3.7
    steps:
      - python_build

workflows:
  version: 2
  build:
    jobs:
      - gcc
      - clang
      - debug

  static-analysis:
    jobs:
      - cppcheck
      - scan-build

  python:
    jobs:
      - python-27
      - python-35
      - python-36
      - python-37
